# Generated by Django 5.0 on 2024-01-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emodji', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
            ],
        ),
    ]
